export const INDUSTRIES = [
  'Agriculture & Agribusiness',
  'Aviation',
  'Construction & Real Estate',
  'Education & Training',
  'Energy & Utilities',
  'Financial Services & Banking',
  'Government & Public Sector',
  'Healthcare & Medical',
  'Hospitality & Tourism',
  'Information Technology & Software',
  'Insurance',
  'Legal Services',
  'Logistics & Transportation',
  'Manufacturing & Industrial',
  'Media, Communications & Entertainment',
  'Mining & Extractives',
  'NGO & Nonprofit',
  'Oil & Gas',
  'Professional & Business Services',
  'Retail & E-commerce',
  'Security Services',
  'Telecommunications',
  'Textiles & Apparel',
  'Water & Sanitation',
  'Other',
];
