// Same card for Twitter/X previews — without this, the twitter:image would
// resolve from the root layout's generic fallback instead of the per-job
// thumbnail generated by opengraph-image.js.
export { default, runtime, revalidate, alt, size, contentType } from './opengraph-image';
