// Same card for Twitter/X previews — without this, the twitter:image would
// resolve from the root layout's generic fallback instead of the per-job
// thumbnail generated by opengraph-image.js. Segment config fields must be
// literals (Next can't statically read re-exported values), so they are
// declared here rather than re-exported.
export const runtime = 'nodejs';
export const revalidate = 3600;
export const alt = 'Job opening on Cazini';
export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';

export { default } from './opengraph-image';
